"""Create Game Model

Revision ID: 757723fde32b
Revises: faebd12f9523
Create Date: 2024-02-13 21:54:38.380398

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757723fde32b'
down_revision = 'faebd12f9523'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
